# Generated by Django 5.1.1 on 2024-10-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0007_individual_age_individual_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
