# Generated by Django 5.1.1 on 2024-10-19 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_proposal_cv_proposal_unique_individual_job_proposal__and_more'),
        ('company', '0001_initial'),
        ('individual', '0002_experience'),
        ('job', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='individual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='individual.individual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
